apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-echo
  name: http-echo
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: http-echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-echo
    spec:
      containers:
        - image: pyrosomeio/http-echo:1.0
          imagePullPolicy: IfNotPresent
          name: http-echo
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command: ["/bin/http-echo"]
          args: ["-listen", "3000", "-text", "hello world"]
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              initialDelaySeconds: 5
              timeoutSeconds: 1
              failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
